16 создать сервис доменный сервис user status
sashapyatkov1999/logisticProgram pull request #21
Opened 2023-12-26 17:03 UTC by sashapyatkov1999

,

2024-01-01 20:51 UTC, Ledford1403 requested changes

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/resources/db/changelog/tables/UserStatus.xml
> +                <sequenceExists sequenceName="USER_STATUS_S+EQ"/>
Лишний плюс

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/resources/db/changelog/tables/File.xml
> +            <column name="CREATED_" type="TIMESTAMP" defaultValue="CURRENT_TIMESTAMP()">
Лишний символ

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/resources/db/changelog/data/TypeDoc.xml
Значение ENABLE не информативно

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/resources/db/changelog/data/Role.xml
Значение ENABLE не информативно

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/java/com/example/logisticprogram/repository/listDocRepository.java
> +public interface listDocRepository extends JpaRepository<ListDoc, Long> {
Названия классов должны быть с большой буквы

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/java/com/example/logisticprogram/mapper/user/UserResponseMapper.java
> +                .setPassword(source.getPassword())
Пароли не отправляем

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/java/com/example/logisticprogram/mapper/user/UserMapper.java
> +        return new User()
Не хватает  полей  login, password, email

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/java/com/example/logisticprogram/dto/request/user/UserAddRequest.java
> +    private Long userStatusId;
Не хватает  логина и пароля

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/java/com/example/logisticprogram/dto/response/user/UserResponse.java
> +    private String password;
Пароль не отдаем

2024-01-01 20:51 UTC, Ledford1403 commented on src/main/java/com/example/logisticprogram/entity/UserRole.java
Лишнего удалил

2024-01-09 08:01 UTC, sashapyatkov1999 commented on src/main/java/com/example/logisticprogram/mapper/user/UserResponseMapper.java
> +                .setPassword(source.getPassword())
21 УДАЛИЛ , но не понял почему тут не отсавляем, думал надо в реквесте его не отправлять

2024-01-11 16:43 UTC, merged