сделал UserDomainServiceTest
sashapyatkov1999/logisticProgram pull request #44
Opened 2024-01-19 15:32 UTC by sashapyatkov1999

сделал UserDomainServiceTest , но не понял для чего private UserResponse getUserResponse() и private User getUser()

2024-01-22 05:48 UTC, Ledford1403 requested changes

2024-01-22 05:48 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
> +        verify(userResponseMapper).from(users);
Не хватает verifyNoMoreInteractions;
 verifyNoInteractions;

2024-01-22 05:48 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
> +
Не хватает verifyNoMoreInteractions;
verifyNoInteractions;

2024-01-22 05:53 UTC, Ledford1403 requested changes

2024-01-22 05:53 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
>      void getAllUsersTest() {
Инициализация всех объектов должна быть в вспомогательных методах

2024-01-22 05:53 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
>      void addUserTest() {
Инициализация всех объектов должна быть в вспомогательных методах

2024-01-22 05:53 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
> +        verify(userRepository).deleteById(id);
Не хватает verifyNoMoreInteractions;
verifyNoInteractions;

2024-01-22 17:25 UTC, sashapyatkov1999 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
> +
а тут не на что писать verifyNoInteractions;

2024-02-13 17:28 UTC, Ledford1403 approved these changes

2024-02-13 17:28 UTC, merged