готово
sashapyatkov1999/logisticProgram pull request #49
Opened 2024-01-28 10:20 UTC by sashapyatkov1999

2024-01-28 22:19 UTC, Ledford1403 requested changes

2024-01-28 22:19 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/DriverDomainServiceTest.java
> +    private final DriverAddRequest driverAddRequestAdd = new DriverAddRequest();
Инициализацию убрать в методы

2024-01-28 22:19 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/DriverDomainServiceTest.java
> +        drivers.add(new Driver(1L));
Инициализацию убрать в методы

2024-01-28 22:19 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/DriverDomainServiceTest.java
> +        driverAddRequestAdd.setId(1L);
Инициализацию убрать в методы

2024-02-15 18:16 UTC, sashapyatkov1999 commented
на проверку с фиксами

2024-02-20 17:37 UTC, Ledford1403 approved these changes

2024-02-20 17:37 UTC, merged