40 юнит тесты для userdomainservice
sashapyatkov1999/logisticProgram pull request #50
Opened 2024-01-28 10:21 UTC by sashapyatkov1999

2024-01-28 22:17 UTC, Ledford1403 requested changes

2024-01-28 22:17 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
Не все тесты 
![image](https://github.com/sashapyatkov1999/logisticProgram/assets/22887058/b5fe0602-85db-4d32-895e-1499c28bd6b5)

2024-01-28 22:17 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
> +    private final UserAddRequest userAddRequestAdd = new UserAddRequest();
Инициализацию убрать в методы

2024-01-28 22:17 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/UserDomainServiceTest.java
> +        users.add(new User(1L));
Инициализацию убрать в методы

2024-02-15 18:57 UTC, sashapyatkov1999 commented
сделал , и конфликты убрал

2024-02-20 17:36 UTC, Ledford1403 approved these changes

2024-02-20 17:36 UTC, merged