37 юнит тесты pointdomainservice
sashapyatkov1999/logisticProgram pull request #51
Opened 2024-01-28 10:31 UTC by sashapyatkov1999

2024-01-28 22:15 UTC, Ledford1403 requested changes

2024-01-28 22:15 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/PointDomainServiceTest.java
> +        points.add(new Point(1L));
Инициализацию убрать в методы

2024-01-28 22:15 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/PointDomainServiceTest.java
> +    private final PointAddRequest pointAddRequestAdd = new PointAddRequest();
Инициализацию убрать в методы

2024-02-16 09:13 UTC, sashapyatkov1999 commented
все исправил

2024-02-20 17:35 UTC, Ledford1403 approved these changes

2024-02-20 17:35 UTC, merged