33 юнит тесты для applicationdomainservice
sashapyatkov1999/logisticProgram pull request #52
Opened 2024-01-28 14:54 UTC by sashapyatkov1999

2024-01-28 22:12 UTC, Ledford1403 requested changes

2024-01-28 22:12 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/ApplicationDomainServiceTest.java
> +        applications.add(new Application(1L));
Инициализацию убрать в методы

2024-01-28 22:12 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/ApplicationDomainServiceTest.java
> +    private final ApplicationAddRequest applicationAddRequestAdd = new ApplicationAddRequest();
Инициализацию убрать в методы

2024-02-16 09:37 UTC, sashapyatkov1999 commented
исправил , можно мерджить

2024-02-20 17:34 UTC, Ledford1403 approved these changes

2024-02-20 17:34 UTC, merged