34 юнит тесты для cardomainservice
sashapyatkov1999/logisticProgram pull request #53
Opened 2024-01-28 17:02 UTC by sashapyatkov1999

2024-01-28 22:06 UTC, Ledford1403 requested changes

2024-01-28 22:06 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/CarDomainServiceTest.java
> +    void getCarByNumber(){
Вынести инициализацию в отдельный метод

2024-01-28 22:06 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/CarDomainServiceTest.java
> +    void getAllCarsTest() {
Вынести инициализацию в методы

2024-01-28 22:09 UTC, Ledford1403 requested changes

2024-01-28 22:09 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/CarDomainServiceTest.java
> +    private final CarAddRequest carAddRequestAdd = new CarAddRequest();
Инициализацию убрать в методы

2024-02-16 14:00 UTC, sashapyatkov1999 commented
сделал но с комментарием

2024-02-17 12:00 UTC, sashapyatkov1999 commented
ВСЕ сделал

2024-02-20 17:33 UTC, Ledford1403 approved these changes

2024-02-20 17:33 UTC, merged