38 юнит тесты для roledomainservice
sashapyatkov1999/logisticProgram pull request #56
Opened 2024-01-28 17:55 UTC by sashapyatkov1999

2024-01-28 21:55 UTC, Ledford1403 requested changes
Тест падает с ошибкой 
![image](https://github.com/sashapyatkov1999/logisticProgram/assets/22887058/a00365cf-3880-47e6-9666-12bdb40dc0d8)

2024-01-28 21:57 UTC, Ledford1403 requested changes

2024-01-28 21:57 UTC, Ledford1403 commented on src/test/java/com/example/logisticprogram/service/domain/RoleDomainServiceTest.java
> +        private final Long id = 1L;
Дубликат переменной

2024-02-16 15:25 UTC, sashapyatkov1999 commented
все сделал

2024-02-20 17:29 UTC, Ledford1403 approved these changes

2024-02-20 17:29 UTC, merged